"""empty message

Revision ID: 2ba364070835
Revises: 8fabfd624ea9
Create Date: 2022-11-16 18:10:02.216721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ba364070835'
down_revision = '8fabfd624ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=252), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('closed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tasklist')
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('user_table_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_table_user_id_fkey', 'tasklist', ['user_id'], ['id'])
        batch_op.drop_column('task_id')

    op.create_table('tasklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=252), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('closed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tasklist_pkey')
    )
    op.drop_table('task')
    # ### end Alembic commands ###
